name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main   # Trigger this action on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "tejoess"
          git config --global user.email "tejassutarofc@gmail.com"

      - name: Push to Hugging Face Space
        run: |
          git remote add hf https://huggingface.co/spaces/tejoess/simple-chatbot
          git push https://tejoess:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/tejoess/simple-chatbot main --force
